"""empty message

Revision ID: 0ee9648b0128
Revises: 905ef6fc67e3
Create Date: 2025-10-02 09:56:40.473898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee9648b0128'
down_revision = '905ef6fc67e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('destino', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('disponibilidade', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('destino')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('periodo', sa.DateTime(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('info')
    # ### end Alembic commands ###
