"""empty message

Revision ID: 3c0cabd87d9b
Revises: 8f5b6da8a443
Create Date: 2025-09-25 08:50:05.710090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0cabd87d9b'
down_revision = '8f5b6da8a443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disponibilidade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.drop_column('disponibilidade')

    # ### end Alembic commands ###
