"""Adiciona campo de descricao em Info

Revision ID: 7b99981e9e7e
Revises: 119d373e570f
Create Date: 2025-10-02 10:08:11.313721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b99981e9e7e'
down_revision = '119d373e570f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.alter_column('destino',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('destino',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
