"""empty message

Revision ID: 83827ce926b1
Revises: 30bc2b6fd584
Create Date: 2025-10-29 11:28:49.601432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83827ce926b1'
down_revision = '30bc2b6fd584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('destino', sa.VARCHAR(length=100), nullable=False),
    sa.Column('preco', sa.INTEGER(), nullable=True),
    sa.Column('data_envio', sa.DATETIME(), nullable=True),
    sa.Column('disponibilidade', sa.INTEGER(), nullable=True),
    sa.Column('categoria', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('destino')
    )
    # ### end Alembic commands ###
