"""empty message

Revision ID: 89b14f5e06dd
Revises: 
Create Date: 2025-09-25 08:08:15.816386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b14f5e06dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('destino', sa.Integer(), nullable=False),
    sa.Column('preço', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.Column('período', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('destino', 'categoria')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('info')
    # ### end Alembic commands ###
