"""empty message

Revision ID: 8f5b6da8a443
Revises: 89b14f5e06dd
Create Date: 2025-09-25 08:29:16.658111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5b6da8a443'
down_revision = '89b14f5e06dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_envio', sa.DateTime(), nullable=True))
        batch_op.alter_column('categoria',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
        batch_op.drop_column('período')
        batch_op.drop_column('preço')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodo', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('periodo')

    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preço', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('período', sa.INTEGER(), nullable=True))
        batch_op.alter_column('categoria',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('data_envio')
        batch_op.drop_column('preco')

    # ### end Alembic commands ###
