"""empty message

Revision ID: 905ef6fc67e3
Revises: 3c0cabd87d9b
Create Date: 2025-10-02 09:14:11.886079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905ef6fc67e3'
down_revision = '3c0cabd87d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('destino', sa.INTEGER(), nullable=False),
    sa.Column('preco', sa.INTEGER(), nullable=True),
    sa.Column('data_envio', sa.DATETIME(), nullable=True),
    sa.Column('categoria', sa.VARCHAR(), nullable=True),
    sa.Column('disponibilidade', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('destino', 'categoria')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('senha', sa.VARCHAR(), nullable=True),
    sa.Column('periodo', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
